# -*- coding: utf-8 -*-
"""luas-segitiga

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0SKEXQYfW1L_8AJvQQEBbwjJrPaWxsJ
"""

# 3. Menghitung luas segitiga

def hitung_luas_segitiga(alas, tinggi):
    return (alas * tinggi) / 2

alas = 25
tinggi = 30
luas = hitung_luas_segitiga(alas, tinggi)

print(f"Luas segitiga: {luas}")