# -*- coding: utf-8 -*-
"""kpk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0SKEXQYfW1L_8AJvQQEBbwjJrPaWxsJ
"""

# 1. Mencari nilai KPK dari 3 dan 4

def cari_kpk(a, b):
    kpk = max(a, b)
    while kpk % a != 0 or kpk % b != 0:
        kpk += max(a, b)
    return kpk

hasil = cari_kpk(3, 4)
print(f"KPK dari 3 dan 4 adalah: {hasil}")