# -*- coding: utf-8 -*-
"""piring

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0SKEXQYfW1L_8AJvQQEBbwjJrPaWxsJ
"""

# 2. Fungsi untuk menukar posisi dua variabel x dan y

def tukar_buah(piring1, piring2):
    piring3 = piring1
    piring1 = piring2
    piring2 = piring3
    return piring1, piring2

piring1 = "manggis"
piring2 = "pisang"
piring1, piring2 = tukar_buah(piring1, piring2)

print(f"Piring 1: {piring1}")
print(f"Piring 2: {piring2}")