# -*- coding: utf-8 -*-
"""jajargenjang

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0SKEXQYfW1L_8AJvQQEBbwjJrPaWxsJ
"""

# 4. Menghitung luas jajar genjang

def hitung_luas_jajar_genjang(panjang, tinggi):
    return panjang * tinggi

panjang = 5
tinggi = 3
luas = hitung_luas_jajar_genjang(panjang, tinggi)

print(f"Luas jajar genjang: {luas}")