# -*- coding: utf-8 -*-
"""Dandy Tri Widianto-Pertemuan 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvDFLmD0yj6iVDQtewdpWE5tSsFuqRXZ

MK DAA Pertemuan 1 Dandy Tri Widianto - 2023071011
"""

# 1. Mencari nilai KPK dari 3 dan 4

def cari_kpk(a, b):
    kpk = max(a, b)
    while kpk % a != 0 or kpk % b != 0:
        kpk += max(a, b)
    return kpk

hasil = cari_kpk(3, 4)
print(f"KPK dari 3 dan 4 adalah: {hasil}")

# 2. Fungsi untuk menukar posisi dua variabel x dan y

def tukar_buah(piring1, piring2):
    piring3 = piring1
    piring1 = piring2
    piring2 = piring3
    return piring1, piring2

piring1 = "manggis"
piring2 = "pisang"
piring1, piring2 = tukar_buah(piring1, piring2)

print(f"Piring 1: {piring1}")
print(f"Piring 2: {piring2}")

# 3. Menghitung luas segitiga

def hitung_luas_segitiga(alas, tinggi):
    return (alas * tinggi) / 2

alas = 25
tinggi = 30
luas = hitung_luas_segitiga(alas, tinggi)

print(f"Luas segitiga: {luas}")

# 4. Menghitung luas jajar genjang

def hitung_luas_jajar_genjang(panjang, tinggi):
    return panjang * tinggi

panjang = 5
tinggi = 3
luas = hitung_luas_jajar_genjang(panjang, tinggi)

print(f"Luas jajar genjang: {luas}")

# 5. Menghitung volume tabung

import math

def hitung_volume_tabung(jari_jari, tinggi):
    return math.pi * jari_jari ** 2 * tinggi

jari_jari = 3
tinggi = 5
volume = hitung_volume_tabung(jari_jari, tinggi)

print(f"Volume tabung: {volume:.2f}")

# 6. Menghitung volume kerucut

def hitung_volume_kerucut(diameter, tinggi):
    jari_jari = diameter / 2
    return (1/3) * math.pi * jari_jari ** 2 * tinggi

diameter = 5
tinggi = 4
volume = hitung_volume_kerucut(diameter, tinggi)

print(f"Volume kerucut: {volume:.2f}")