# -*- coding: utf-8 -*-
"""kerucut

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0SKEXQYfW1L_8AJvQQEBbwjJrPaWxsJ
"""

# 6. Menghitung volume kerucut

def hitung_volume_kerucut(diameter, tinggi):
    jari_jari = diameter / 2
    return (1/3) * math.pi * jari_jari ** 2 * tinggi

diameter = 5
tinggi = 4
volume = hitung_volume_kerucut(diameter, tinggi)

print(f"Volume kerucut: {volume:.2f}")