# -*- coding: utf-8 -*-
"""Dandy Tri Widianto-Pertemuan02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5m8eZAlqzxGMyQDXld7JhX5Q0g4HzID

MK DAA Latihan pertemuan ke 2
Dandy Tri Widianto - 2023071011
"""

import numpy as np

a = [1,2,3]
b = [4,5,6]

hasil = a + b
print(sum(hasil))



def total_matriks(list):
  total = 0
  for i in list:
    total += i
  return total
a = [1,2,3]
b = [4,5,6]

total_ab = np.add(a, b)
print(total_matriks(total_ab))

def totallist(list1,list2):
  total = 0
  for i in list1:
    total +=i
  for i in list2:
    total+=i
  return total

totallist(a,b)

nilai_siswa = np.array([85,55,40,90])
print(nilai_siswa[3])

=nama = input("Masukkan Nama Anda : ")
NIM = int(input("Masukkan NIM Anda : "))

print("Hello, World!")
print(f"Nama saya {nama} ")
print(f"NIM saya {NIM}")

if 5>2:
  print("Five is greater than two!")

if 2>5:
  print("Five is greater than two!")

x = 5
y = "John"
print(x)
print(y)

x = 4
x = "Sally"
print(x)

def getFirst(myList):
  return myList[0]

getFirst([1, 2, 3])
getFirst([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

def getSecond(myList):
  return myList[1]

getSecond([1, 2, 3])
getSecond([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

def getLast(myList):
  return myList[-1]

getLast([1, 2, 3])
getLast([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

def getlast2(list):
  size = len(list)
  print(f"Size: {size}")
  return list[size-1]

getlast2([1,2,3,4,5,6])

def getKali(list):
  kali = 1
  for i in list:
    kali *= i
  return kali

getKali([1,3,5,7])

def getBagi(list):
  bagi = 1
  for i in list:
    bagi /= i
  return bagi

getBagi([60,3,5,7])